version: '3'
services:
  recorder:
    build:
      context: .
    env_file: .env
    networks:
      - default
  mysql:
    image: mysql:5.7
    env_file: .mysql.env
    networks:
      - default
networks:
  default:
