# Prototyping services for development
version: '3'
services:
  mysql:
    image: mysql:8.0
    volumes:
      - ./.data:/var/lib/mysql-files
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fillarivahti
      MYSQL_USER: fillarivahti
      MYSQL_PASSWORD: fillarivahti
    networks:
      - default
    ports:
      - 3306
  redis:
    image: redis:6
    ports:
      - 6379
    networks:
      - default
networks:
  default:
